#Not auto-registering this bundle for safety reasons. 
#Manually define in AppKernel scenarios when this bundle should be loaded
#bundles:
#    - { name: Aaxis\Bundle\DevToolsBundle\AaxisDevToolsBundle }
